### ISSUE TITLE
Automatic build on push to main? Caching problems?

### ISSUE THREAD

**Issue by lillijo** [udk-berlin/rundgang-website-2024#6]
1. trigger action on push to main
2. make sure that old status is not cached? right now I am still getting 
![image](https://github.com/udk-berlin/rundgang-website-2024/assets/38139300/d6d4a563-c436-471b-bb35-e5cb142f0d88)
when opening https://rundgang-frontend-24.dev.medienhaus.udk-berlin.de/
3. possibly change `.env` again, to show old api and not new, empty one?

**Comment by andirueckel** [comment]
@lillijo Can you privately send me the `.env` file you need?
